version: 2.1

orbs:
    node: circleci/node@4.7.0
    browser-tools: circleci/browser-tools@1.3.0
    coveralls: coveralls/coveralls@1.0.6

jobs:
    test_player:
        docker:
            - image: cimg/node:18.1.0-browsers
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: npm
            - browser-tools/install-chrome
            - browser-tools/install-chromedriver
            - run:
                  name: Headless Chrome tests
                  command: npm test
            - run:
                  name: Send results to Coverage
                  command: echo 'done'

workflows:
    end-to-end-tests:
        jobs:
            - test_player
